name: Plex
description: |
  Plex media server.
version: 0.0.2-rancher1
category: Media Server
maintainer: Gavin Brown
license: GNU General Public License v3.0
projectURL: https://github.com/greycubesgav/rancher-plex