name: Plex
description: |
  Plex media server.
version: 0.0.1-rancher1
category: Media Server
maintainer: Siim
license: GNU General Public License v3.0
projectURL: https://github.com/simpss/rancher-plex